### PR TITLE
fix: `MSSQL` Suggestion to fix null schemaName when the table is a view

### PR DESCRIPTION
**Pull request by liozme**
I verified this in our MSSQL database. 
There were 2 indexes from views that had null schemas.
i added the logic to add schema_name to views (that have schema_id)
then if the s.NAME is null, take v.schema_name (like table_name)

### CODE REVIEW

**Review by cofin — APPROVED** [review]
lgtm

**Comment by PholphatPhumkaew** [comment]
You guys are very talented. I accept you.

**Review by shane-borden — COMMENTED** [review]
LGTM.

**Comment by PholphatPhumkaew** [comment]
Yes yeah!🏡🤔🧐🌄🤗🆗

**Pull request merged**
