### PR TITLE
feat: Store pkey, sourceID and manualId when machine specs fails.

### PR DESCRIPTION
**Pull request by YairHalberstadt**
Fixes b/353893181

### CODE REVIEW

**Comment by YairHalberstadt** [comment]
PTAL @shane-borden Thanks

**Review by shane-borden — CHANGES_REQUESTED** [review]
The empty fields need to either also have double quotation marks or utilize the word NULL to represent an empty value.  Preferably the empty double quote option is preferred.

**Comment by YairHalberstadt** [comment]
> The empty fields need to either also have double quotation marks or utilize the word NULL to represent an empty value. Preferably the empty double quote option is preferred.

Done

**Review by shane-borden — APPROVED** [review]
LGTM

**Pull request merged**
